### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by jayabal90** [john-smilga/gatsby-strapi-portfolio-site-2020#1]
how to give Permissions in content-types at gatsby-config file.

**Comment by jayabal90** [comment]
G:\GatsbyDevelopment\gatsby-strapi-portfolio\src\pages\index.js
  29:5  error  Cannot query field "allStrapiProjects" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


File: src\pages\index.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


G:\GatsbyDevelopment\gatsby-strapi-portfolio\src\pages\projects.js
  23:5  error  Cannot query field "allStrapiProjects" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


File: src\pages\projects.js

**Comment by tiff0000** [comment]
I have the same issue

**Comment by john-smilga** [comment]
Well if you want to run a complete project, you also need a backend otherwise you are going to get an error.

**Comment by MeRabia** [comment]
> I have the same issue

hello did you figure out this problem cuz I have the same issue

**Comment by danielotieno** [comment]
Any solution to this? @john-smilga  I haven't understood your answer kindly elaborate. Thanks

**Comment by mnai01** [comment]
> Any solution to this? @john-smilga I haven't understood your answer kindly elaborate. Thanks

I had to update my strapi to fix the problem. Just update all the [dependencies](https://strapi.io/documentation/developer-docs/latest/guides/update-version.html#upgrade-your-dependencies) then clean the build ` npm run build -- --clean` and start the app. Goodluck
