### ISSUE TITLE
Generating development JavaScript bundle failed

### ISSUE THREAD

**Issue by garlen-javier** [john-smilga/gatsby-strapi-portfolio-site-2020#3]
I just started watching your youtube tutorial.
Follow the initial steps.
1. Download source code at github
2. Unzip and open in vscode
3. npm install
4. gatsby develop

And here I got this errors.
![portfolio_error](https://user-images.githubusercontent.com/71249192/107441253-e60bb180-6b6f-11eb-96a3-90e19c7c13aa.PNG)
.

**Comment by lucasffs** [comment]
I am facing the same issue over here.

**Comment by john-smilga** [comment]
Of course. Please check gatsby-config.js - it's expecting a working strapi app. Please watch the video first

**Comment by garlen-javier** [comment]
The steps on your video is totally not in order, so confusing, in the video you show the gatsby deployment first but your github project has dependencies for strapi which is not in the first steps on your video.

**Comment by john-smilga** [comment]
I  suggest getting the correct repo first. This is for complete project
